version: '3'
services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
        # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  backend:
    build: backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    labels:
      - traefik.http.routers.backend.rule=Host(`backend.localhost`)
  frontend:
    build: frontend
    command: bash -c "npm start"
    volumes:
      - ./frontend:/app
    ports:
      - 3000
    depends_on:
      - backend
    labels:
      - traefik.http.routers.frontend.rule=Host(`frontend.localhost`)
