source 'https://rubygems.org'
gem 'rails', '~>6'
gem 'pg', '1.1.4'
gem 'rss', '0.2.8'
gem 'rack-cors', '1.0.3'

group :test do
  gem 'rspec'
end

group :development, :test do
  gem 'database_cleaner', '~> 1.7.0'
  gem 'factory_bot', '4.11.1'
  gem 'byebug'
  gem 'rspec-rails', '3.8.1'
  gem 'timecop', '0.9.1'
  gem 'listen', '3.2.0'
end
